TIANTIAN/TIANTIAN/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

TIANTIAN/app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('index/', views.index, name='index'),
    path('list/', views.goods_list, name='list'),
    path('detail/', views.detail, name='detail'),
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('order/', views.order, name='order'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('login/', views.login, name='login'),
    path('center_info/', views.center_info, name='center_info'),
    path('center_order/', views.center_order, name='center_order'),
    path('center_site/', views.center_site, name='center_site'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),


]

pachongxiazai/xiangmuyanshi/xiangmuyanshi/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

TIANTIAN/app/models.py
from django.db import models
from django.core import validators
import datetime


class User(models.Model):
    """用户信息"""
    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    username = models.CharField(
        verbose_name='用户名', unique=True, max_length=30,
        validators=[validators.MinLengthValidator(limit_value=6, message='用户名不能少于6位')]
    )
    password = models.CharField(
        verbose_name='密码', max_length=30,
        validators=[
            validators.MinLengthValidator(limit_value=8, message='密码不能少于8位')
        ]
    )
    email = models.EmailField(
        verbose_name='邮箱', unique=True
    )

def validate_unique(self, exclude=None):
    super().validate_unique(exclude=['username'])


class Category(models.Model):
    """分类信息"""
    name = models.CharField('名称', max_length=10, unique=True)
    icon = models.ImageField('图片样式')

def upload_thumb(instance, filename):
    return '{0}_{1}.png'.format(
        instance.id, datetime.datetime.strftime(datetime.datetime.now(), '%Y%m%d%H%M%S')
    )


class Goods(models.Model):
    """商品信息"""
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField('名称', max_length=30)
    price = models.DecimalField('价格', max_digits=5, decimal_places=2)
    thumb = models.ImageField('主图', upload_to=upload_thumb, null=True, blank=True)


class Cart(models.Model):
    """购物车"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    goods = models.ManyToManyField(Goods, through='CartGoods', through_fields=('cart', 'goods'))


class CartGoods(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)
    number = models.SmallIntegerField(default=0)

class Userinfo(models.Model):
    '''用户信息表，输入地址相关'''
    class Meta:
        verbose_name = '用户信息表'
        verbose_name_plural = verbose_name
    address = models.CharField('地址',max_length=100)
    phone = models.CharField('电话',max_length=11)
    recipient = models.CharField('收件人',max_length=10)
    postcode = models.CharField('邮编',max_length=6)
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='用户')
    def __str__(self):
        return self.name


class OrderInfo(models.Model):
    """订单信息"""
    class Meta:
        verbose_name = '订单信息'
        verbose_name_plural = verbose_name
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    goods = models.ManyToManyField(Goods, through='OrderGoods', through_fields=('order_info', 'goods'), verbose_name='商品')
    #status = models.SmallIntegerField('订单状态', choices=[(0, '未确认'), (1, '确认'), (2, '已取消'), (3, '无效'), (4, '退货')])
    pay_status = models.SmallIntegerField('支付状态', choices=[(0, '未付款'),(1, '已付款')])
    shipping_status = models.SmallIntegerField('配送状态', choices=[(0, '未发货'), (1, '已发货'), (2, '已收货'), (3, '退货 ')])
    add_time = models.DateTimeField('创建时间', auto_now_add=True)
    def __str__(self):
        return self.name

class OrderGoods(models.Model):
    """订单商品（订单和商品是多对多关系，该表是中间表）"""
    order_info = models.ForeignKey(OrderInfo, on_delete=models.CASCADE, verbose_name='订单ID')
    goods = models.ForeignKey(Goods, '商品ID')
    number = models.SmallIntegerField('数量')

TIANTIAN/app/forms.py
from django.forms import ModelForm, widgets
from django import forms
from .models import User

"""
form 表单主要实现的功能：
1. 可以生成模板中的相应的表单控件标签
2. 对表单中填写的数据进行相应规则的验证
3. 验证不通过的非法数据进行错误提示并显示在模板中
form 表单的实现流程：
1. 根据需要的表单字段定义Form类
   a. 如果表单上的数据不是模型中的数据，则form类继承django.forms.Form类
   b. 如果表单上的数据是模型中的字段，则form类继承django.forms.ModelForm类
2. 定义Form类中的字段
   a. 如果是非模型Form，字段的定义方式与模型字段的定义方式基本一致
   b. 如果是模型Form，通过Meta类指定对应的模型类以及使用的模型字段
   c. 字段定义中，通过validators属性指定验证规则以及错误提示信息内容
3. 在视图中根据请求方式：
   a. 如果是get请求表单页面，则实例化一个空的Form对象，并传入模板中，在模板中
      输出该对象即可得到表单的控件标签
   b. 如果是post请求提交表单数据，则使用post数据实例化一个Form对象，然后调用
      form对象的is_valid()方法验证数据，该方法返回True则验证通过，否则验证
      失败
   c. 如果验证失败，再把form对象返回客户端浏览器，则展示带有错误提示的表单
      如果验证通过，通过form.cleaned_data属性可以得到表单数据的一个字典
      通过该属性获取数据继续后面的操作
"""


class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': widgets.TextInput(attrs={'class': 'name_input', 'placeholder': '请输入用户名'}),
            'password': widgets.PasswordInput(attrs={'class': 'pass_input', 'placeholder': '请输入密码'})
        }


class RegisterForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']
    password2 = forms.CharField(max_length=10, label='确认密码')

TIANTIAN/app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import LoginForm, RegisterForm
from .models import User, Category, Goods, Cart, CartGoods,Userinfo,OrderGoods,OrderInfo
from django.core.paginator import Paginator
import math


def index(request):
    """首页"""
    categories = Category.objects.all()
    return render(request, 'index.html', {
        'categories': categories,
        'user': request.session.get('user')
    })


def goods_list(request):
    gjz = request.GET.get('q')
    if gjz != None:
        try:
            goods = Goods.objects.filter(name__icontains=gjz)
        except Exception:
            return HttpResponse('不存在该商品')
        paginator = Paginator(goods, 2)
        # 4. 获取页码
        num = request.GET.get('num', 1)
        # 5. 通过页码初始化当前页面的Page对象
        page = paginator.page(num)

        # 6. 返回响应结果
        return render(request, 'list.html', {
            'page': page,
            'goods':goods,
            'user': request.session.get('user'),
            'q': gjz
        })

    # 1. 获取分类ID
    category_id = request.GET.get('category_id')
    # 2. 根据分类ID查询该分类下面的所有商品
    try:
        goods = Category.objects.get(pk=category_id).goods_set.all()

    except Exception:
        return HttpResponse('不存在商品')
    # 3. 初始化Paginator分页类的对象
    paginator = Paginator(goods, 2)
    # 4. 获取页码
    num = request.GET.get('num', 1)
    # 5. 通过页码初始化当前页面的Page对象
    page = paginator.page(num)
    # 6. 返回响应结果
    return render(request, 'list.html', {
        'page': page,
        'category_id': category_id,
        'user': request.session.get('user'),

    })


def detail(request):
    goods_id = request.GET.get('goods_id')
    good = Goods.objects.get(pk=goods_id)

    return render(request, 'detail.html', {'goods': good,
                                           'user': request.session.get('user')})

# def detail(request, goods_id):
#     try:
#         goods = Goods.objects.get(pk=goods_id)
#         cart_goods_count = Cart.objects.get(user__username=request.session.get('user')).cartgoods_set.all().count()
#     except Exception:
#         return HttpResponse('不存在该商品')
#     print(cart_goods_count)
#     return render(request, 'detail.html', {'goods': goods, 'cart_goods_count': cart_goods_count})


def cart(request):
    cart = Cart.objects.get(user__username=request.session.get('user')).cartgoods_set.all()
    num = cart.count()
    return render(request, 'cart.html', {'car': cart,
                                         'num': num,
                                         'user': request.session.get('user')})


def add_to_cart(request):
    # 获取请求提交的商品id和数量
    goods_id = request.POST.get('goods_id')
    number = request.POST.get('number')
    try:
        # get_or_create 返回 (object, created) object是数据对象，
        # created为布尔值，true为创建的数据，false为查询的数据
        # 获取当前用户的购物车
        cart = Cart.objects.get_or_create(
            user__username=request.session.get('user'),
            defaults={
                'user_id': User.objects.get(username=request.session.get('user')).id
            }
        )
    except Exception:
        return HttpResponse('没有该用户')
    # 给当前用户的购物车添加或更新商品数量
    cartgoods = CartGoods.objects.update_or_create(cart=cart[0], goods_id=goods_id)

    cartgoods[0].number += int(number)
    cartgoods[0].save()
    # 返回结果
    if cartgoods[0]:
        return HttpResponse(cart[0].cartgoods_set.count())
    else:
        return HttpResponse('添加失败')




def order(request):
    import json
    # 获取到被选中到商品的ID们
    cartgoods = json.loads(request.GET.get('data'))
    ids = []
    for item in cartgoods:
        ids.append(item['cartgoods_id'])
        CartGoods.objects.filter(pk=item['cartgoods_id']).update(number=item['number'])
    data = CartGoods.objects.filter(id__in=ids)
    return render(request,'place_order.html',{'cartgoods':data,
                                              'user': request.session.get('user')})

# def goods_list(request):
#     """商品列表页面"""
#     # 获取get请求传递低参数
#     category_id = request.GET.get('category_id')
#     # 从页面获取当前点击的页码（转成整数类型）
#     page = int(request.GET.get('page', 1))
#     is_first = True
#     if page != 1:
#         is_first = False
#     # 获取当前分类下的所有商品
#     goods = Category.objects.get(pk=category_id).goods_set.all()
#     # 计算总页码
#     pages = range(1, math.ceil(goods.count() / 1) + 1)
#     return render(request, 'list.html', {
#         'category_id': category_id,
#         'goods': goods[(page-1)*1:(page-1)*1+1],
#         'pages': pages,
#         'is_first': is_first
#     })


def register(request):
    """用户注册处理"""
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create(
                username=data['username'],
                password=data['password'],
                email=data['email'],
            )
            if user is not None:
                return render(request,'index.html')
            else:
                return HttpResponse('注册失败')
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})


def login(request):
    """用户登录处理"""
    if request.method == 'POST':
        # 用表单提交过来的数据创建一个LoginForm对象
        form = LoginForm(request.POST)
        # 判断表单数据是否合法
        if form.is_valid():
            data = form.cleaned_data
            try:
                user = User.objects.get(
                    username=data['username'],
                    password=data['password']
                )
            except Exception:
                return HttpResponse('用户名密码错误')
            # 登录成功, 需要将当前登录的用户保存记录下来
            # 使用session存储数据，可以在服务端进行全局共享
            request.session['user'] = user.serializable_value('username')
            return redirect('index')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

def center_info(request):
    user_id = User.objects.get(username=request.session.get('user')).id
    add = Userinfo.objects.filter(user_id=user_id,id=1)
    return render(request,'user_center_info.html',{'add':add,
                                                   'user':request.session.get('user')})


def center_order(request):
    user_id = User.objects.get(username=request.session.get('user')).id
    dingdans = OrderInfo.objects.filter(user_id=user_id)
    paginator = Paginator(dingdans, 1)
    # 4. 获取页码
    num = request.GET.get('num', 1)
    # 5. 通过页码初始化当前页面的Page对象
    page = paginator.page(num)
    # 6. 返回响应结果
    price = OrderGoods.objects.filter(order_info__user_id=user_id).all()
    a = 0
    for i in price:
        a += i.goods.price * i.number

    return render(request, 'user_center_order.html', {
        'page': page,
        'user': request.session.get('user'),
        'a':a,
    })

def center_site(request):
    if request.method == 'POST':
        recipient = request.POST.get('recipient')
        address = request.POST.get('address')
        postcode = request.POST.get('postcode')
        phone = request.POST.get('phone')
        user_id = User.objects.get(username=request.session.get('user')).id
        user = Userinfo.objects.create(
            recipient=recipient,address=address,postcode=postcode,phone=phone,user_id=user_id
        )
        if user is not None:
            return render(request,'user_center_site.html')
        else:
            return HttpResponse('提交失败')

    return render(request,'user_center_site.html',{'user':request.session.get('user')})


def add(request):
    #添加订单商品到数据库
    user_id = User.objects.get(username=request.session.get('user')).id
    ordergoods_id = request.POST.get('ordergoods_id')
    aa = ordergoods_id.strip().split(',')
    print(aa)
    cartgoods = CartGoods.objects.filter(id__in=aa)
    print(cartgoods)
    order = OrderInfo.objects.create(user_id=user_id,pay_status=0,shipping_status=0)
    for i in cartgoods:
        ordergoods = OrderGoods.objects.create(
            order_info=order,goods=i.goods,number=i.number
        )
    if ordergoods:
        #点击删除按钮同步删除数据库商品
        CartGoods.objects.filter(id__in=aa).delete()
    return render(request,'user_center_order.html')


def delete(request):
    cart_goods_id=request.GET.get('cart_goods_id')
    goods_id = CartGoods.objects.filter(id=cart_goods_id).delete()
    return redirect('cart')


TIANTIAN/templates/cart.html
{% extends 'base.html' %}
{% block title %}购物车{% endblock title %}
{% block content %}
    {% load staticfiles %}

{% block ccc %}{% endblock ccc %}
	<div class="total_count">全部商品<em>{{ num }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

    {% for id in car %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input class="select" type="checkbox" name="" checked data-id ={{id.id}}></li>
		<li class="col02"><img src="{{ MEDIA_URL }}{{ id.goods.thumb }}"></li>
		<li class="col03">{{ id.goods.name }}<br><em>{{ id.goods.price }}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{ id.goods.price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ id.number }}">
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">25.80元</li>
		 <li class="col08"><a href="{% url 'delete' %}?cart_goods_id={{ id.id }}">删除</a></li>
	</ul>

	{% endfor %}
	<ul class="settlements">
		<li class="col01"><input id="selectAll" type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="total">42.60</em><br>共计<b id="count">2</b>件商品</li>
		<li class="col04"><a id="jiesuan" href="{% url 'order' %}">去结算</a></li>
	</ul>
    <script>
        $('#jiesuan').click(function () {
            {#获取被选中的复选框#}
            cartgoods = []
            $('.select:checked').each(function (i,el) {
                num = $(el).parents('ul').find('.num_show').val()
                id = $(el).attr('data-id')
                cartgoods.push({'number':num,'cartgoods_id':id})
            })
            console.log(cartgoods)
            $(this).attr('href',"{% url 'order' %}?data=" + JSON.stringify(cartgoods))


        })
    </script>
{#    <script >src="{% static 'jquery-1.12.4.min.js' %}"></script>#}
    <script>

		$('.add').click(function(){
			// 获取原来的数量
			var n = parseInt($(this).next('.num_show').val())
			// 给数量加1
			$(this).next('.num_show').val(n+1)
			$('.num_show').change()
			// // 获取商品单价
			// price = parseFloat($(this).parent().parent().prev().html()) * 100
			// // 计算小计
			// sum = price * (n+1)
			// // 获取小计的元素并赋值
			// $(this).parent().parent().next().text(sum/100 + '元')
		});
		$('.minus').click(function(){
			var n = parseInt($(this).prev('.num_show').val())
			if(n>0){
				$(this).prev('.num_show').val(n-1)
				$('.num_show').change()
				// // 获取商品单价
				// price = parseFloat($(this).parent().parent().prev().html()) * 100
				// // 计算小计
				// sum = price * (n-1)
				// // 获取小计的元素并赋值
				// $(this).parent().parent().next().text(sum/100 + '元')
			}
		})
		$('.num_show').change(function() {
			// 获取商品单价
			price = parseFloat($(this).parent().parent().prev().html()) * 100
			// 计算小计
			sum = price * $(this).val()
			// 获取小计的元素并赋值
			$(this).parent().parent().next().text((sum/100).toFixed(2) + '元')

			// 计算总价
			var total = 0
			$('.col07').each(function(i, el){
				if($(this).parents('ul').find('.select').get(0).checked) {
					total += parseFloat($(el).text()) * 100
				}
			})
			$('#total').text((total/100).toFixed(2))
		})

		// 选择框改变，处理价格和数量计算
		$('.select').change(function() {
			n = parseInt($('#count').text())
			if(this.checked) {
				$('#count').text(n+1)
			} else {
				if(n > 0){
					$('#count').text(n-1)
				}
			}
			$('.num_show').change()
		})
		// 点击全选，计算价格和数量
		$('#selectAll').change(function(){
			checked = this.checked
			$('.select').each(function(i,el){
				el.checked = checked
			})
			$('.select').change()
		})
    </script>

{% endblock content %}

TIANTIAN/templates/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ goods.name }}{% endblock title %}
{% block content %}
{% csrf_token %}

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ MEDIA_URL }}{{ goods.thumb }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.name }}</h3>
			<p>草莓浆果柔软多汁，味美爽口，适合速冻保鲜贮藏。草莓速冻后，可以保持原有的色、香、味，既便于贮藏，又便于外销。</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="ox">{{ goods.price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input id="goods_num" type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr" id="add_num">+</a>
					<a href="javascript:;" class="minus fr" id="minu_num">-</a>
				</div> 
			</div>
			<div class="total">总价：<em id="oo">元</em></div>
			<div class="operate_btn">
				<a href="{% url 'cart' %}?goods_id={{ goods.id }}" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>草莓采摘园位于北京大兴区 庞各庄镇四各庄村 ，每年1月-6月面向北京以及周围城市提供新鲜草莓采摘和精品礼盒装草莓，草莓品种多样丰富，个大香甜。所有草莓均严格按照有机标准培育，不使用任何化肥和农药。草莓在采摘期间免洗可以直接食用。欢迎喜欢草莓的市民前来采摘，也欢迎各大单位选购精品有机草莓礼盒，有机草莓礼盒是亲朋馈赠、福利送礼的最佳选择。 </dd>
				</dl>
			</div>

		</div>
	</div>

	<div class="add_jump"></div>

	<script type="text/javascript">
        {# 数量的加减操作 #}
        $('#add_num').click(function () {
            {# jq的val()等同于js的 value 属性 #}
            $('#goods_num').val(parseInt($('#goods_num').val())+1)
            $('#oo').html(parseInt($('#goods_num').val()) * $('#ox').html())
        })
        $('#minu_num').click(function () {
            {# jq的val()等同于js的 value 属性 #}
            if($('#goods_num').val() > 0){
                $('#goods_num').val(parseInt($('#goods_num').val())-1)
                $('#oo').html(parseInt($('#goods_num').val()) * $('#ox').html())
            }
        })



		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast');

			});


		    {# 异步请求加入购物车 #}
            $.ajax({
                url: {% url 'add_to_cart' %},
                type: 'POST',
                {#将CSRF-Token返回服务端#}
                headers: {
                    'X-CSRFTOKEN': $.cookie('csrftoken')
                },
                data: {
                    goods_id: {{ goods.id }},
                    number: $('#goods_num').val()
                },
                success: function (res) {
                    $('#show_count').html(res);
                }
            })
		})

	</script>
	{% endblock content%}

TIANTIAN/templates/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}首页{% endblock title %}

{% block content %}

<div class="center_con clearfix">
    <ul class="subnav fl">
        {% for category in categories %}
            <li><a href="{% url 'list' %}?category_id={{ category.id }}" class="{{ category.icon }}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>

    <div class="slide fl">
        <ul class="slide_pics">
            <li style="left: -760px;"><img src="{% static 'slide.jpg' %}" alt="幻灯片"></li>
            <li style="left: 0px;"><img src="{% static 'slide02.jpg' %}" alt="幻灯片"></li>
            <li style="left: 760px;"><img src="{% static 'slide03.jpg' %}" alt="幻灯片"></li>
            <li style="left: 760px;"><img src="{% static 'slide04.jpg' %}" alt="幻灯片"></li>
        </ul>
        <div class="prev"></div>
        <div class="next"></div>
        <ul class="points">
            <li class=""></li>
            <li class="active"></li>
            <li></li>
            <li></li>
        </ul>
    </div>
    <div class="adv fl">
        <a href="http://www.xiaozhican.top/shop/index/#"><img src="{% static 'adv01.jpg' %}"></a>
        <a href="http://www.xiaozhican.top/shop/index/#"><img src="{% static 'adv02.jpg' %}"></a>
    </div>
</div>

{% for category in categories %}
    <div class="list_model">
    <div class="list_title clearfix">
        <h3 class="fl" id="model01">{{ category.name }}</h3>
        <a href="http://www.xiaozhican.top/shop/categorys/1/" class="goods_more fr" id="fruit_more">查看更多 &gt;</a>
    </div>
    <div class="goods_con clearfix">
        <div class="goods_banner fl"><img src="{{ MEDIA_URL }}{{ category.icon }}"></div>
        <ul class="goods_list fl">
            {% for goods in category.goods_set.all|slice:':4' %}
                <li>
                    <h4><a href="{% url 'detail' %}?goods_id={{ goods.id }}">{{ goods.name }}</a></h4>
                    <a href="{% url 'detail' %}?goods_id={{ goods.id }}">
                        <img src="{{ MEDIA_URL }}{{ goods.thumb }}">
                    </a>
                    <div class="prize">¥ {{ goods.price }}</div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endfor %}

{% endblock content %}

TIANTIAN/templates/user_center_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ goods.name }}{% endblock title %}
{% block content %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'center_order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>

            {% for dingdan in page.object_list %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ dingdan.add_time }}</li>
					<li class="col02">{{ dingdan.id }}</li>
					<li class="col02 stress"></li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order in dingdan.ordergoods_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{{ MEDIA_URL }}{{ order.goods.thumb }}"></li>
									<li class="col02">{{ order.goods.name }}<em>{{ order.goods.price }}元/500g</em></li>
									<li class="col03">{{ order.number }}</li>
									<li class="col04">{{ order.goods.price }}元</li>
								</ul>
								{% endfor %}

							</td>
							<td width="15%">{{ a }}</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>

					</tbody>
				</table>
        {% endfor %}
				<div class="pagenation">
                    {% for page in page.paginator.page_range %}
                    <a href="{% url 'center_order' %}?num={{ page }}"
                       class="active" style="background-color: #1b6d85">{{ page }}</a>
                    {% endfor %}

				</div>
		</div>
	</div>


{% endblock content %}